### ISSUE TITLE
Naming is not intuitive and confusion with User Schema

### ISSUE THREAD

**Issue by edisonzsq** [Kern000/projectTwoBackendServer#1]
Your code are message you write to another developer who will continue your work. 

1. Your `user-schema.js` is returning `EntrySchema`. This is confusing.
2. What is `keyOfDataArray` and `nestedDataKey` in your controller and service?

I would say there will be a `UserSchema` that stores user-related data and another `EntrySchema` to store data not related to user. Usually we try to not mix these together.

**Comment by Kern000** [comment]
Hi Edison, just to clarify as I want to avoid a referencing model and instead use embedded to store all the information of a user and his/her activities in one document, so I kind of tied the userSchema and EntrySchema together since all the entry and CRUD will be tied to a user, can I rename it as UserEntrySchema?

**Comment by Kern000** [comment]
keyOfDataArray Targets the key in database that holds an array as its values, other keys in mongo will be string datatype value, so it is differentiated as the frontend CRUD will be performed via different pages.

This keyOfDataArray namely the countryCode, blockedNumbers, whiteList will further branch into two kinds of data structure.
countryCode will be an array of strings.
blockedNumbers and whiteList will have an object containing a blockedNumber and a timestamp for sorting for time sorted display on frontend.
Thus, Nested Data key targets the key of an object nested in an array, namely the blockedNumber for targeting the specify number to perform CRUD on it.

**Comment by edisonzsq** [comment]
For the schema design. User Schema in practice has to be separated and referenced. I personally will not accept such DB design for production code.

For the `keyOfDataArray`, you can rename it and make it more intuitive. You can explain to me now. But if you are working in a development team of 20, you have to explain to 20 people. Then why not make the variable name more intuitive? This won't be straight forward becuz it's not easy to give a good name, it takes practice. You can also consider putting yourself in other developer's shoes and how can you write your code and give good name that will help developers understand the meaning of the variable at a glance.

**Comment by Kern000** [comment]
Hi Edison, completed separation of concerns by separating user and entry schema and reworked the respective functions in the service, controller, and router layers. Renamed the variables and params for greater clarity. Should be more intuitive now.
