### ISSUE TITLE
Where should you catch error?

### ISSUE THREAD

**Issue by edisonzsq** [Kern000/projectTwoBackendServer#2]
In the `entry-service.js`, there is this piece of code:

```js
const updateFieldData = async (userId, keyOfField, data) =>{
    try{
        let foundUser = await EntryModel.findById(userId);
            if (foundUser){
                let foundKey = foundUser.hasOwnProperty(keyOfField)
                foundUser[keyOfField] = data[keyOfField]
                const savedUser = await foundUser.save();
                return savedUser;
            } else {
            throw new Error("User not found"); // (1) When you throw here
            }
        } catch (error) {
            throw error; (2) It will be caught here. You did nothing but throw again. In this case, you do not need to catch it here.
        }
}
``` 
You have to ask yourself which layer should handle the error? usually it's the controller layer. you will then use `try-catch` in the controller to catch any error thrown from service layer and handle it from there.

In this case, your `try-catch` is redundant as it does nothing after it caught it.

**Comment by Kern000** [comment]
This one, front end will be using API interceptor to handle error there, not sure if that would work. I believe I was trying to throw it to higher levels. What would be a good alternative here?

**Comment by edisonzsq** [comment]
We don't mix frontend and backend code. The responsibility of the developer in the backend code will not be responsible for the frontend code. Even if you have done something in the frontend, it has nothing to do with the backend.

**Comment by Kern000** [comment]
Have completed the amendments to remove try catch in the service layer, throw New Error to catch in controller instead. More streamlined. Thank you.
