### ISSUE TITLE
Not handling enough alternate flow and understanding of http status

### ISSUE THREAD

**Issue by edisonzsq** [Kern000/projectTwoBackendServer#3]
Let's take the controller function `createProfile` as an example:

```js
const createProfile = async (req, res) => {
    try{
        await createEntry(req.body);
        return res.sendStatus(httpStatus.CREATED);
    } catch (error) {
        console.log("Profile creation failed", error);
        return res.sendStatus(httpStatus.INTERNAL_SERVER_ERROR);
    }
}
```

You have not handled:
- Data validation failed, returns bad request status
- I assume the `EntrySchema.emailAddress` is used to identify a unique user. You should also check if the user already exist. If it exist, you may also return a http conflict status

You can identify the above unhandled scenarios by giving your error object a certain message of use of a custom code. When you catch the error in controller, you will then inspect the error object to return the respective status code. There will be more than one way to tackle this.

**Comment by Kern000** [comment]
Hi Edison, I have updated comments on this in the file. This route is purely for testing and admin purpose, will be commented out by the final product. It serves no purpose other than for me to YARC sanity test.

**Comment by Kern000** [comment]
Data structure was also changed to match Firebase structure in your notes. So the schema no longer holds email address field as not holding user email and password was clearly the superior choice rather than to perform Bcrypt password hashing on an app level.

**Comment by edisonzsq** [comment]
The `createProfile` function is just an example. You have to review all your code to ensure you have handled alternate flows. 

So I won't know whether your code is going to be used for now or will be removed in the future. As long as the code is there, then I will judge it. Unless you removed them. =D

**Comment by Kern000** [comment]
Thanks, removed redundant codes and git merge the necessary branch to master.
