### ISSUE TITLE
Logging for traceability

### ISSUE THREAD

**Issue by edisonzsq** [Kern000/projectTwoBackendServer#7]
The principle of traceability will help you locate production issue as quickly as possible. In order to achieve the traceability principle, we need to implement logging. A popular JS library for logging would be [winston](https://www.npmjs.com/package/winston). 

In most cloud based application, we would log to console and it will be streamed to a centralized log collector. 

Simply google "How can I perform logging for Node Application" you'll find many results. I'll kick you off with the first reference [here](https://medium.com/geekculture/winston-logger-in-javascript-16d54dbe931f)

**Comment by Kern000** [comment]
Thanks Edison, I will look into this on a future date.
